ingress:
  className: ""
  annotations: {}
  hosts:
    - host: test.hyunjin.kr
      paths:
        - path: /
          pathType: Prefix
          serviceName: traffico-api
          servicePort: 3000
  tls: []
