replicaCount: 8
image:
  repository: willom2c/traffico-api
  pullPolicy: IfNotPresent
  tag: "sha-da8521b62a2aaa7a0959dac71d192c7227a7bebf"
service:
  type: ClusterIP
  port: 3000
serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
  path: /metrics
  port: http
  interval: 15s
resources:
  requests:
    cpu: 1000m
    memory: 512Mi
nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - hash-n97-1
topologySpread:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  matchLabelKeys:
    - pod-template-hash
