replicaCount: 1
image:
  repository: willom2c/traffico-api
  pullPolicy: IfNotPresent
  tag: "sha-db37d033fbcfa08cf3d0a29ec06d2e1701b0e853"
service:
  type: ClusterIP
  port: 3000
serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
  path: /metrics
  port: http
  interval: 15s
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
