replicaCount: 1
image:
  repository: willom2c/traffico-api
  pullPolicy: IfNotPresent
  tag: "sha-5bc14bf82c012dabaa9b57412bcd5b98896a3c9c"
service:
  type: ClusterIP
  port: 3000
serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
  path: /metrics
  port: http
  interval: 15s
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
