apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traffico-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/makeUgreat/traffico.git
    path: deploy/helm/traffico-api
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: traffico
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
